boneIO - ssr dimmer
maciejkrasuski/boneIO pull request #73
Opened 2021-12-07 19:24 UTC by Voytho

2021-12-07 21:38 UTC, maciejkrasuski requested changes
Hej - na wstępie dzięki wielkie za zaangażowanie w projekt!

Mam jednak trochę uwag i sugestii:
1. JP1 jest na tej płytce zbędny - on jest wrzucony jeśli ktoś by chciał zastosować przekaźniki 5v, a tu one nie występują:
![image](https://user-images.githubusercontent.com/70077751/145108235-fc62d872-7a67-4ea7-be5f-bfb414966287.png)

2. Czujniki temperatury - dałeś dla obydwu typów ten sam footprint, a dla lm75 powinien być inny (skopiuj z aktualnej wersji relayboard, która jest na masterze).

3. Fajnie jakby zachować standard rozmieszczenia elementów na płytkach dolnych (logo po lewej, czujniki temp po prawej)

4. Do wybierania adresów MCP daj lutowane zworki plus rezystory podciągające (patrz aktualne wersje na GH)
![image](https://user-images.githubusercontent.com/70077751/145108722-7c44b3fb-6a86-4929-bb9d-82c6045045aa.png)

5. Wylanie masy - nie rób ścieżek pod masą (wylej całościowo)
![image](https://user-images.githubusercontent.com/70077751/145108985-e1e7b5bd-3945-4b73-a421-035117c99ee4.png)

6. Ścieżki 230V daj grubsze (2.5mm) i daj je po obydwu stronach płytki i po stronie back zostaw bez soldermaski, jakby trzeba było nalać cyny dla większych prądów.
![image](https://user-images.githubusercontent.com/70077751/145109248-31113d9f-8d83-4a40-9e5d-2ceb9690596e.png)

7. Poprowadź ścieżki trochę bliżej siebie, aby nie zostawiać takich pustych przestrzeni bez masy
![image](https://user-images.githubusercontent.com/70077751/145109362-18fbb6e3-45fc-4937-9487-1a1488c40030.png)

8. Warystor wchodzi w obudowę - trzeba go przesunąć w głąb płytki. Triak jest za blisko konektorów od input board - też trzeba go przesunąć w stronę środka płytki
![image](https://user-images.githubusercontent.com/70077751/145109812-a106c034-99bb-4b27-a036-604870e46d41.png)

9. Po drugiej stronie triak wchodzi w obudowę - też trzeba przesunąć
![image](https://user-images.githubusercontent.com/70077751/145109891-66a1db21-e02b-4c6a-88b0-c2451c8d4072.png)

Na ten moment tyle - myślę, że więcej uwag będą mieli bardziej obcykani spece od Kicada niż ja ;)

2021-12-07 21:55 UTC, Voytho commented
Dzięki za uwagi. Robiłem trochę w ciemno, ale teraz już wiem co i jak. Oczywiście poprawki naniosę jak najszybciej. Ze wszystkim się zgadzam, ale mam sugestię co do triaków. Pomyślałem, że docelowo "położy" się je na brzuchu. plecami do góry, co da większą możliwość kombinowania z radiatorami.

2021-12-07 22:09 UTC, maciejkrasuski commented
> Dzięki za uwagi. Robiłem trochę w ciemno, ale teraz już wiem co i jak. Oczywiście poprawki naniosę jak najszybciej. Ze wszystkim się zgadzam, ale mam sugestię co do triaków. Pomyślałem, że docelowo "położy" się je na brzuchu. plecami do góry, co da większą możliwość kombinowania z radiatorami.

No spoko - to dobry pomysł... ciekawe w sumie jak to będzie się grzało.

2021-12-09 13:57 UTC, Voytho commented
Kończę poprawki. Mam tylko trzy pytania. 

1. Ścieżki mogą mieć maksymalnie 2.3mm ze względu na odległości pinów np. triaka. Może tak zostać? Nic innego nie jestem w stanie wymyślić.
2. Prowadząc ścieżki wysokoprądowe po obu stronach, muszę zastosować przelotki ze względu na rezystory SMD. Przejdzie? Jakieś sugestie?
3. Istnieje sposób na odcięcie zaokrąglenia ścieżki w miejscu granicy pada?

![Bez tytułu](https://user-images.githubusercontent.com/8394097/145409713-9c90f471-8d70-455d-97f7-9bbd3a81755c.png)


Pozostałe rzeczy już poprawione.
Pozdrawiam

2021-12-09 22:29 UTC, Voytho commented
Poprawiłem, chociaż nie jestem do końca zadowolony. Te przelotki przy dimmerach (przyjmijmy że to te u dołu pcb) jakoś mi się nie podobają. Daj proszę znać czy coś z tego będzie. Wszelkie słowa krytyki biorę na klatę, wkładam w plecak i idziemy dalej :D Pozdrawiam.

2021-12-11 08:48 UTC, kamil2466 commented
@Voytho 
Patrzyłem twój projekt i mam parę propozycji zmian:
1. FUSE są za duże footprinty wystarczy ze będą 2512
2. Tak się zastanawiam jak by BT136 odwrócić o 180 stopni to by można było go pochylić w stronę MOC
3. Proponuje jak się uda wszystkie rezystory dać na stronie TOP może uda się w chinach położyć te elementy, JLCPCB tylko 1 stronę układa wiec musi być wszystko na 1 stronie

Jeszcze sprawa do @maciejkrasuski odnośnie numeracji płytek ja bym zrobił numeracje v0.1 dla dimmer nie musimy się trzymać numeracji od Input Board bo i tak nam się to rozjedzie.

2021-12-11 08:52 UTC, kamil2466 commented
@Voytho odnośnie tego obrócenia BT136 to jest sprawa do przemyślenia widzę ze teraz fajnie pasuje do MOC3041 a obrócenie pogorszy prowadzenie ścieżek.

2021-12-11 12:37 UTC, Voytho commented
Fuse rzeczywiście za duże dałem. Poprawię. BT136 bym zostawił tak jak są, a rezystory spokojnie położę na jednej stronie z pozostałymi. Numeracja płytki - fakt. Może być myląca, więc zostawię v0.1. Mam tylko prośbę, co do sugestii odnośnie przelotek po stronie HV. Może tak zostać?

2021-12-11 13:06 UTC, kamil2466 commented
Wydaje mi się że nie będzie problemu z przelotkami na rezystorach. Można też zrobić 2 przelotki obok siebie na 1 ścieżce będzie lepiej przewodził duży prąd

2021-12-11 19:39 UTC, Voytho commented
Poprawione według wskazówek. Wszystkie elementy z jednej strony. Wzmocnione ścieżki HV. Poprawiona numeracja płyty.

2021-12-11 20:45 UTC, maciejkrasuski requested changes
Hej,
Przeanalizowałem tak na szybko ułożenie elementów względem obudowy i jeszcze delikatne poprawki by się przydały:
![image](https://user-images.githubusercontent.com/70077751/145691071-2fbeadaf-efec-45ef-a754-e39339911c40.png)
Radiator triaka domyślnie wypada na stykach inputów - jakbyś go przesunął jeszcze z 1mm do środka płytki to nawet jeśli ktoś go nie pochyli to nie zrobi zwarcia.
Warystor z 0.5mm do środka aby nie stykał się z obudową jak ktoś nierówno wlutuje.

2021-12-12 22:02 UTC, Voytho commented
Przesunąłem triaki i warystory. Myślę, że tak już będzie dobrze. Proszę o dokładne sprawdzenie projektu w wolnym czasie. Byłbym wdzięczny. Pozdrawiam.

2021-12-12 22:49 UTC, kamil2466 commented
@Voytho wprowadź jeszcze 1 zmianę weź jumpery na stronie bottom umieść, bedzie lepsze dojście do zmiany adresacji.

2021-12-12 22:59 UTC, Voytho commented
Wszystkie sekcje?

2021-12-13 00:11 UTC, Voytho commented
Poprawione. Moje pytanie było zbędne :)

2021-12-19 11:55 UTC, maciejkrasuski approved these changes

2021-12-19 11:55 UTC, merged